apiVersion: v1
kind: ReplicationController
metadata:
  name: frontend-rc
  labels:
    app: guestbook
    tier: frontend
spec:
  replicas: 3
  template:
    metadata:
      name: frontend
      labels:
        app: guestbook
        tier: frontend
    spec:
      containers:
      - name: nginx-container
        image: nginx
        ports:
        - containerPort: 80